package com.cjsheehan.jrace.racing;

public enum RunnerState {
	ENTERED, DECLARED, NON_RUNNER, FINISHED, UNSEATED_RIDER, PULLED_UP, FELL, REFUSED, RAN_OUT, BROUGHT_DOWN, SLIPPED, DISQUALIFIED, VOID, NOT_AVAILABLE
}
